### ISSUE TITLE
Lambda functions and Persistent Query (APQ)

### ISSUE THREAD

**Issue by golfingal72** [flochaz/federated-appsync-api-demo#5]
I'm not that familiar, but I don't think lambda processes continue running for a long time...

When using the Apollo Federated gateway with APQ, the gateway actually keeps a cache of those APQ id's so that it does not continually have to re-parse incoming large queries...  

If the gateway is run as a lambda function and restarts all the time, it seems to me that we would lose the cache and have to re-parse those queries over and over again?

APQ provides significant performance enhancements for large queries.

**Comment by golfingal72** [comment]
Yes, that is exactly what would be needed!!  

https://www.apollographql.com/docs/apollo-server/performance/apq/

I don't think DynamoDB is the place because of the churn and it's NOT the fastest, but Redis or memcached would be ideal

**Comment by flochaz** [comment]
After doing some digging I can tell you that it is not part of Appsync Roadmap. Would be great if you could create a feature request here: https://github.com/aws/aws-appsync-community/issues . If this get a bit of traction I'll be happy to add an example of such implementation in the meantime (waiting for AppSync to add the official support). Otherwise always happy to take PR ;)
